spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 88b23adbc991a7c17224
            clientSecret: 5b87f3815ee55f7de53f84c50ef7899cc81614bd
            #authorizationGrantType: authorization_code
